### ISSUE TITLE
Way to clear option fed_admin_login['login_menu']

### ISSUE THREAD

**Issue by adnoh** [mavinothkumar/frontend-dashboard#13]
Hello,
in the backend you can set the frontend login menu, but you can never clear this setting (exept of clearing the hole fed_admin_login option in tools).
It would be great to just unset that part of the config array fed_admin_login['login_menu'] on that page or in the tools

**Comment by fetitxe** [comment]
https://github.com/mavinothkumar/frontend-dashboard/pull/14#issue-406586718
